### PR TITLE
Figma to tailwind 

### PR DESCRIPTION
**Pull request by Avinashshiyani**
# Figma to React + Tailwind CSS Conversion

This repository showcases my conversion of a Figma design into a React application styled with Tailwind CSS.

## 📋 Pull Request Details

- **Figma Design**: Converted to a React + Tailwind application.
- **Responsive Design**: Ensures a seamless user experience across all devices.
- **Path Added**: The page has been added to `/admin/shop/singleitem` as the exact path was unknown.

## 🚀 Getting Started

Follow these instructions to set up the project locally:

### Prerequisites

- Node.js
- npm or yarn

### Installation

1. Clone the repository:

   ```bash
   git clone https://github.com/AvinashShiyani/your-repo-name.git

### CODE REVIEW

**Comment by Avinashshiyani** [comment]
@sonylomo  i have tried but i am not able to understand eslint error so now what can i do to resolve this errror ?

**Comment by sonylomo** [comment]
> @sonylomo i have tried but i am not able to understand eslint error so now what can i do to resolve this errror ?

I've fixed them for you. Thank you for your contribution. 🚀

**Review by sonylomo — CHANGES_REQUESTED** [review]
The `Edit` button the table row doesn't display the edit form that you created. The Edit form should pop up once the user clicks the `Edit` button on the table.

**Comment by Avinashshiyani** [comment]
> The `Edit` button the table row doesn't display the edit form that you created. The Edit form should pop up once the user clicks the `Edit` button on the table.

Ok i will Change this And Make This issue Undraft .

**Comment by sonylomo** [comment]
In case you're stuck/blocked, please notify me so I can help you. 🙂

**Comment by Avinashshiyani** [comment]
I am not stucked but I am busy till 20-8-2024 for some reasons so I will be starting work from 21-8-2024 but I will do your work before 1-9-2024 @sonylomo

**Comment by sonylomo** [comment]
Hey @Avinashshiyani 👋🏾

Would you like me to help you finish this task? It is time sensitive at the moment.

**Comment by Avinashshiyani** [comment]
> Hey @Avinashshiyani 👋🏾
> 
> Would you like me to help you finish this task? It is time sensitive at the moment.
> 

By the way sorry for taking too long and yes I need your last help , I will undraft the pull request so you can make changes .

**Pull request closed without merging**
