### PR TITLE
Felix community page links mobile

### PR DESCRIPTION
**Pull request by Ase020**

### CODE REVIEW

**Review by Ase020 — COMMENTED** [review]
@sonylomo, thanks for adding the links. I think it would be better if we used the `Link` tags instead of the generic `a` when working with `react-router-dom`.

**Review by sonylomo — APPROVED** [review]
LGTM 🫰🏾

**Comment by sonylomo** [comment]
> @sonylomo, thanks for adding the links. I think it would be better if we used the `Link` tags instead of the generic `a` when working with `react-router-dom`.

As a best practice, `Link` is used when navigating to relative URLs provided by React Router e.g `/events`, `/community` e.t.c. However, `a` is for user-clickable hyperlinks to external pages/ absolute page links e.g "https://...`.

**Comment by Ase020** [comment]
> > @sonylomo, thanks for adding the links. I think it would be better if we used the `Link` tags instead of the generic `a` when working with `react-router-dom`.
> 
> @Ase020 As a best practice, `Link` is used when navigating to relative URLs provided by React Router e.g `/events`, `/community` e.t.c. However, `a` is for user-clickable hyperlinks to external pages/ absolute page links e.g "https://...`. WDYT?

Ok. For this case, let's go with the `a` tags. Thanks for this new info. Everyday we learn something new.😅

**Review by JimmyTron — APPROVED** [review]

**Pull request merged**
