### PR TITLE
Related-blogs

### PR DESCRIPTION
**Pull request by Ase020**

### CODE REVIEW

**Comment by JimmyTron** [comment]
Not rendering the page

**Comment by Ase020** [comment]
Screenshot 2024-01-07 210523
Screenshot 2024-01-07 210554

**Comment by Ase020** [comment]
> 
> 
> Not rendering the page

It should be fine now.

**Review by JimmyTron — CHANGES_REQUESTED** [review]
Screenshot 2024-01-07 213354
 I queried this using the blog id and it gave me the same blog as related. 
 
 this maybe because it uses the slug for identification

**Comment by Ase020** [comment]
> Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> 
> this maybe because it uses the slug for identification

@JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object.
Screenshot 2024-01-07 225753

**Comment by collinskasyoki** [comment]
> > Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> > this maybe because it uses the slug for identification
> 
> @JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object. Screenshot 2024-01-07 225753

Seems to be a backend issue.

**Comment by collinskasyoki** [comment]
> > Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> > this maybe because it uses the slug for identification
> 
> @JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object. Screenshot 2024-01-07 225753

@Ase020 Since you already have the id of the blog, can you just filter it out from the results of the related blogs on the frontend?

**Comment by Ase020** [comment]
> > > Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> > > this maybe because it uses the slug for identification
> > 
> > 
> > @JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object. Screenshot 2024-01-07 225753
> 
> @Ase020 Since you already have the id of the blog, can you just filter it out from the results of the related blogs on the frontend?

@collinskasyoki I don't understand. Can you please explain further.

**Comment by Ase020** [comment]
Screenshot 2024-01-08 225621
Screenshot 2024-01-08 225819

Spinner Loaders

**Review by JimmyTron — APPROVED** [review]

**Comment by Ase020** [comment]
> > > > > Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> > > > > this maybe because it uses the slug for identification
> > > > 
> > > > 
> > > > @JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object. Screenshot 2024-01-07 225753
> > > 
> > > 
> > > @Ase020 Since you already have the id of the blog, can you just filter it out from the results of the related blogs on the frontend?
> > 
> > @collinskasyoki I don't understand. Can you please explain further?
> 
> Use a filter and get rid of the blog matching the currently selected blog. So if we are on the blog with id 1, and another list of related blogs with ids [1, 2, 3], we can filter out 1 to remain with only 2 and 3. 

It's done that way.

**Comment by collinskasyoki** [comment]
> > > > > > Screenshot 2024-01-07 213354 I queried this using the blog id and it gave me the same blog as related.
> > > > > > this maybe because it uses the slug for identification
> > > > > 
> > > > > 
> > > > > @JimmyTron could this be a backend issue? I think querying the api using id should return a 404 error response and not the blog object. Screenshot 2024-01-07 225753
> > > > 
> > > > 
> > > > @Ase020 Since you already have the id of the blog, can you just filter it out from the results of the related blogs on the frontend?
> > > 
> > > 
> > > @collinskasyoki I don't understand. Can you please explain further?
> > 
> > 
> > Use a filter and get rid of the blog matching the currently selected blog. So if we are on the blog with id 1, and another list of related blogs with ids [1, 2, 3], we can filter out 1 to remain with only 2 and 3.
> 
> It's done that way.

Fixed. It doesn't show up now even when accessed through id.

**Review by collinskasyoki — APPROVED** [review]

**Pull request merged**
