### PR TITLE
Blog page format

### PR DESCRIPTION
**Pull request by Ase020**
1. Span the width of footer to 100% 
Screenshot 2024-01-03 141737

2. Format the blogs page and individual page 
Screenshot 2024-01-03 143135
Screenshot 2024-01-03 143152

### CODE REVIEW

**Comment by Ase020** [comment]
Screenshot 2024-01-03 144126
Screenshot 2024-01-03 144300
Added line clamps to PodcastCard titles & desc to prevent overflow

**Comment by Ase020** [comment]
1. Add the search functionality 
Screenshot 2024-01-04 153924

2. Add some styling to blog body 
Screenshot 2024-01-04 153953

**Review by JimmyTron — APPROVED** [review]
Nothing Breaks... LGTM

**Comment by sonylomo** [comment]
Screenshot 2024-01-05 at 11 34 40 AM
The banner would look better if it spanned the width of the whole screen (remove padding around it). Otherwise, it LGTM 💪🏾.

**Comment by Ase020** [comment]
> Screenshot 2024-01-05 at 11 34 40 AM The banner would look better if it spanned the width of the whole screen (remove padding around it). Otherwise, it LGTM 💪🏾.

@sonylomo  The max-width of the page is set 1440px that's why it looks that on large screens, on screens with widths less than 1440px, it spans the whole width.

**Review by sonylomo — APPROVED** [review]

**Pull request merged**
