### PR TITLE
Felix landing page redesign

### LINKED ISSUE #70: MVP: Home Page
- [x] Implement the new and improved [home page design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=4275-6389&mode=design&t=k0qaA2HouDiVfMuR-0)
- [x] Set a max-width for the welcome hero section (about 1440px) for xl screens.
- [x] Add correct links to all buttons
- [ ] #74
- [x] Implement carousel on podcast cards

### LINKED ISSUE #73: MVP: Footer link fixes
## Description

- Some links on the footer aren't linked to actual routes.
- For the MVP, we'll only need these pages on the navbar:
   - Home
   - About Us
   - Community

## Tasks

- [x] Add required routes to the footer links
- [x] Comment out footer links that are not required for the MVP

### PR DESCRIPTION
**Pull request by Ase020**
Fixes #70 
Fixes #73

### CODE REVIEW

**Review by sonylomo — APPROVED** [review]
LGTM. Great work @Ase020 🙌🏾

**Review by JimmyTron — CHANGES_REQUESTED** [review]
# The hero Image was changed in the design

Kindly check the correct iteration on the design file
image

**Comment by sonylomo** [comment]
> Kindly check the correct iteration on the design file
The main branch wasn't merged into this branch. It's all good now. 🙂

**Review by JimmyTron — APPROVED** [review]
LG

**Pull request merged**
