### PR TITLE
Related blogs header

### PR DESCRIPTION
**Pull request by Ase020**
Added related blogs header
Screenshot 2024-01-11 103329

### CODE REVIEW

**Comment by collinskasyoki** [comment]
@Ase020 @JimmyTron 


Should the related blogs heading be hidden when there are no related blogs?
image

**Comment by Ase020** [comment]
> @Ase020 @JimmyTron 
> 
> 
> Should the related blogs heading be hidden when there are no related blogs?
> image
> 

I've added the conditional rendering

**Review by collinskasyoki — APPROVED** [review]

**Comment by Oukomondi** [comment]
Yes, when there are no related blogs, it should be absent. The wording should be "Related articles", because related blogs implies that there are other blogs out there related to ours hehe.

**Comment by Oukomondi** [comment]
@collinskasyoki is the thumbs up feature working?

**Comment by collinskasyoki** [comment]
> @collinskasyoki is the thumbs up feature working?

Backend functionality is working. The only thing remaining is integrating it to the frontend.

**Review by JimmyTron — APPROVED** [review]

**Pull request merged**
