### PR TITLE
Feat: about page

### PR DESCRIPTION
**Pull request by sonylomo**
Fixes issue #8

### CODE REVIEW

**Review by JimmyOty — CHANGES_REQUESTED** [review]
image

Looks nice already, We could work on the fonts.

**Comment by sonylomo** [comment]
Do you mean the font style, sizes and weights in different layouts of the website?

**Review by aurakei — APPROVED** [review]

**Comment by hamisirizwan** [comment]
spy_2
spy_1

hello @sonylomo the about page looks cool, Just a little changes on the first three sections.

**Comment by hamisirizwan** [comment]
@sonylomo The paddings on the x axis for the first two sections are pushing them more to the middle. The images and for the first two sections a abit large compared to the designs. On the mission and vision section, check on the resposiveness of the section on mobile

**Review by JimmyTron — APPROVED** [review]

**Pull request merged**
