### PR TITLE
New resources page build

### PR DESCRIPTION
**Pull request by Ase020**
Build skeleton resources page
Screenshot 2023-11-29 160527

### CODE REVIEW

**Comment by JimmyTron** [comment]
Screenshot 2023-12-02 213130

**Review by collinskasyoki — CHANGES_REQUESTED** [review]
The resources link should be commented out, as work on implementing the backend has not started yet.

**Review by Ase020 — COMMENTED** [review]
Changes done.

**Review by JimmyTron — APPROVED** [review]

**Comment by JimmyTron** [comment]
image

Check on the transition at this point it isnt as smooth

**Review by sonylomo — APPROVED** [review]

**Pull request merged**
