### PR TITLE
Donate page -  UI fix

### LINKED ISSUE #61: UI fix: Donate Page
The Donate page has some inconsistency with the [Figma design](https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=1113-7655&mode=design&t=v9HqbCbVkTBeXRdy-0). 

⭐️  The goal is to implement a UI that's as close to the Figma designs as possible for both mobile and desktop layouts. 

These are some examples (feel free to rectify fixes that haven't been highlighted 👇 ):

 First, you can start by fixing spelling mistakes. 🙂

**Desktop view:**
The column cards are supposed to be 3 instead of 4.
Image

**Mobile view:**

Image

### PR DESCRIPTION
**Pull request by davidkrupa**
- spelling
- 3 columns on the desktop
- content position on a single product page

Fixes #61

### CODE REVIEW

**Comment by sonylomo** [comment]
Hey @davidkrupa, thank you for your contribution. I have some suggestions:

1. There's a border that should be hidden on mobile view.
2. The buttons should be laid out on top of each other.

Screenshot 2023-09-13 at 10 07 34 AM

This is the Figma design for reference:
Screenshot 2023-09-13 at 10 11 19 AM

**Comment by davidkrupa** [comment]
@sonylomo
Please check if everything is ok. This was my first pull request ever and I'm bit worried😉

Changes:

- reduced horizontal padding to widen content
- hidden border
- hidden divider
- added logos
- hidden text above buttons & next to logos
- changed some font sizes and weights

buttons:
- layout
- vertical padding
- font size and weight

Some fonts appear bolder than in the Figma design. To change this, it may be needed to update Google Fonts import.

**Review by hamisirizwan — COMMENTED** [review]
@davidkrupa please check on the alignment of the buttons on a mobile screen on the singeDonateProduct Page in reference to the figma designs

https://www.figma.com/file/QZwtseXogSFjLNz64uLwjV/SYT-Website-Redesign-Complete?type=design&node-id=1113%3A7655&t=xSmmgQWxa0Z31bfo-1

**Comment by davidkrupa** [comment]
@hamisirizwan
What do you mean by this? Buttons seem to be alligned as in Figma design. Below 
alignment

**Review by sonylomo — APPROVED** [review]
LGTM

**Pull request merged**
