### PR TITLE
Fix: A Billion Lint Errors in dev 😭😭

### PR DESCRIPTION
**Pull request by sonylomo**
# Fix: A Billion Lint Errors in dev 😭😭

 - [x] Bug fix
 - [ ] New feature

# Proposed changes
⛑️ An attempt at fixing lint errors that have been causing failed tests
🚀 Partly fixes issue #212 

# Warning

Please read these points carefully and answer honestly with an `X`
into all the boxes. Example : [X] 

Before submitting a *pull request* make sure you have:

 - [x] Read the guidelines for contributing.
 - [ ] Wrote some tests.
 - [x] Respected the linting guidelines.

### CODE REVIEW

**Comment by sonylomo** [comment]
@alvyynm, the Lint tests finally passed 🙌🏾
image

I went through almost 300 files trying to fix about **950 Lint errors** 😭

Please check if all routes are functional 😁

**Comment by sonylomo** [comment]
All that's left is updating the PR template

**Comment by JimmyTron** [comment]
Despite the billion fixes the deployment still fails 🥲

**Comment by alvyynm** [comment]
Hi @sonylomo, sorry for the late reply. Going over this now. Great work btw.

**Review by alvyynm — DISMISSED** [review]
LGTM.
 
All the routes are functional. The only issue is the failing deployment preview, but I wouldn't worry about that because we've had deployment previews fail and work fine both in staging and production.

**Comment by sonylomo** [comment]
> Despite the billion fixes the deployment still fails 🥲

@JimmyTron Could I get a screenshot of the failed Vercel deployment logs?

**Comment by JimmyTron** [comment]
> > Despite the billion fixes the deployment still fails 🥲
> 
> @JimmyTron Could I get a screenshot of the failed Vercel deployment logs?

```sql 
[15:56:03.299] Running build in Washington, D.C., USA (East) – iad1
[15:56:03.487] Cloning github.com/spaceyatech-org/SYT-Web-Redesign (Branch: Dev, Commit: 8474c2d)
[15:56:05.317] Previous build caches not available
[15:56:06.640] Cloning completed: 3.150s
[15:56:07.360] Running "vercel build"
[15:56:07.804] Vercel CLI 34.3.0
[15:56:08.563] Detected pnpm-lock.yaml version 9 generated by pnpm 9
[15:56:08.581] Installing dependencies...
[15:56:09.326]  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
[15:56:09.326] 
[15:56:09.327] Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
[15:56:09.327] 
[15:56:09.327]     Failure reason:
[15:56:09.327]     specifiers in the lockfile ({"@emailjs/browser":"^3.11.0","@headlessui/react":"^1.7.15","@hookstate/core":"^4.0.1","@tanstack/react-query":"^5.22.2","@tanstack/react-query-devtools":"^5.24.0","@tanstack/react-table":"^8.17.3","axios":"^1.6.1","class-variance-authority":"^0.7.0","clsx":"^2.1.1","date-fns":"^2.30.0","html-react-parser":"^5.0.6","lucide-react":"^0.395.0","million":"^3.0.2","prop-types":"^15.8.1","react":"^18.2.0","react-dom":"^18.2.0","react-fast-marquee":"^1.6.2","react-helmet-async":"^2.0.5","react-hook-form":"^7.48.2","react-hot-toast":"^2.4.1","react-icons":"^5.2.1","react-lazy-load-image-component":"^1.6.0","react-photo-album":"^2.3.0","react-router-dom":"^6.11.2","react-share":"^5.1.0","react-simple-wysiwyg":"^2.2.5","tailwind-merge":"^2.3.0","tailwind-scrollbar-hide":"^1.1.7","tailwindcss-animate":"^1.0.7","yet-another-react-lightbox":"^3.15.6","@playwright/test":"^1.44.1","@types/node":"^20.14.1","@types/react":"^18.0.28","@types/react-dom":"^18.0.11","@vitejs/plugin-react":"^4.0.0","autoprefixer":"^10.4.19","concurrently":"^8.2.2","eslint":"^8.43.0","eslint-config-airbnb":"^19.0.4","eslint-config-prettier":"^9.1.0","eslint-plugin-import":"^2.27.5","eslint-plugin-jsx-a11y":"^6.7.1","eslint-plugin-prettier":"^5.1.3","eslint-plugin-react":"^7.32.2","eslint-plugin-react-hooks":"^4.6.0","husky":"^8.0.0","knip":"^4.6.0","postcss":"^8.4.38","prettier":"^3.3.2","tailwindcss":"^3.4.3","typescript":"^5.4.5","vite":"^5.0.0","vitest":"^1.6.0"}) don't match specs in package.json ({"@playwright/test":"^1.44.1","@types/node":"^20.14.1","@types/react":"^18.0.28","@types/react-dom":"^18.0.11","@vitejs/plugin-react":"^4.0.0","autoprefixer":"^10.4.19","concurrently":"^8.2.2","eslint":"^8.43.0","eslint-config-airbnb":"^19.0.4","eslint-config-prettier":"^9.1.0","eslint-plugin-import":"^2.27.5","eslint-plugin-jsx-a11y":"^6.7.1","eslint-plugin-prettier":"^5.1.3","eslint-plugin-react":"^7.32.2","eslint-plugin-react-hooks":"^4.6.0","husky":"^8.0.0","knip":"^4.6.0","postcss":"^8.4.38","prettier":"^3.3.2","tailwindcss":"^3.4.3","typescript":"^5.4.5","vite":"^5.0.0","vitest":"^1.6.0","@emailjs/browser":"^3.11.0","@headlessui/react":"^2.1.2","@hookstate/core":"^4.0.1","@tanstack/react-query":"^5.22.2","@tanstack/react-query-devtools":"^5.24.0","@tanstack/react-table":"^8.17.3","axios":"^1.6.1","class-variance-authority":"^0.7.0","clsx":"^2.1.1","date-fns":"^2.30.0","html-react-parser":"^5.0.6","lucide-react":"^0.395.0","million":"^3.0.2","prop-types":"^15.8.1","react":"^18.2.0","react-dom":"^18.2.0","react-fast-marquee":"^1.6.2","react-helmet-async":"^2.0.5","react-hook-form":"^7.48.2","react-hot-toast":"^2.4.1","react-icons":"^5.2.1","react-lazy-load-image-component":"^1.6.0","react-photo-album":"^2.3.0","react-router-dom":"^6.11.2","react-share":"^5.1.0","react-simple-wysiwyg":"^2.2.5","recharts":"^2.12.7","tailwind-merge":"^2.3.0","tailwind-scrollbar-hide":"^1.1.7","tailwindcss-animate":"^1.0.7","yet-another-react-lightbox":"^3.15.6"})
[15:56:09.343] Error: Command "pnpm install" exited with 1
[15:56:09.568]
```

**Comment by CodedVeli** [comment]
> > > Despite the billion fixes the deployment still fails 🥲
> > 
> > 
> > @JimmyTron Could I get a screenshot of the failed Vercel deployment logs?
> 
> ```sql
> [15:56:03.299] Running build in Washington, D.C., USA (East) – iad1
> [15:56:03.487] Cloning github.com/spaceyatech-org/SYT-Web-Redesign (Branch: Dev, Commit: 8474c2d)
> [15:56:05.317] Previous build caches not available
> [15:56:06.640] Cloning completed: 3.150s
> [15:56:07.360] Running "vercel build"
> [15:56:07.804] Vercel CLI 34.3.0
> [15:56:08.563] Detected pnpm-lock.yaml version 9 generated by pnpm 9
> [15:56:08.581] Installing dependencies...
> [15:56:09.326]  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
> [15:56:09.326] 
> [15:56:09.327] Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
> [15:56:09.327] 
> [15:56:09.327]     Failure reason:
> [15:56:09.327]     specifiers in the lockfile ({"@emailjs/browser":"^3.11.0","@headlessui/react":"^1.7.15","@hookstate/core":"^4.0.1","@tanstack/react-query":"^5.22.2","@tanstack/react-query-devtools":"^5.24.0","@tanstack/react-table":"^8.17.3","axios":"^1.6.1","class-variance-authority":"^0.7.0","clsx":"^2.1.1","date-fns":"^2.30.0","html-react-parser":"^5.0.6","lucide-react":"^0.395.0","million":"^3.0.2","prop-types":"^15.8.1","react":"^18.2.0","react-dom":"^18.2.0","react-fast-marquee":"^1.6.2","react-helmet-async":"^2.0.5","react-hook-form":"^7.48.2","react-hot-toast":"^2.4.1","react-icons":"^5.2.1","react-lazy-load-image-component":"^1.6.0","react-photo-album":"^2.3.0","react-router-dom":"^6.11.2","react-share":"^5.1.0","react-simple-wysiwyg":"^2.2.5","tailwind-merge":"^2.3.0","tailwind-scrollbar-hide":"^1.1.7","tailwindcss-animate":"^1.0.7","yet-another-react-lightbox":"^3.15.6","@playwright/test":"^1.44.1","@types/node":"^20.14.1","@types/react":"^18.0.28","@types/react-dom":"^18.0.11","@vitejs/plugin-react":"^4.0.0","autoprefixer":"^10.4.19","concurrently":"^8.2.2","eslint":"^8.43.0","eslint-config-airbnb":"^19.0.4","eslint-config-prettier":"^9.1.0","eslint-plugin-import":"^2.27.5","eslint-plugin-jsx-a11y":"^6.7.1","eslint-plugin-prettier":"^5.1.3","eslint-plugin-react":"^7.32.2","eslint-plugin-react-hooks":"^4.6.0","husky":"^8.0.0","knip":"^4.6.0","postcss":"^8.4.38","prettier":"^3.3.2","tailwindcss":"^3.4.3","typescript":"^5.4.5","vite":"^5.0.0","vitest":"^1.6.0"}) don't match specs in package.json ({"@playwright/test":"^1.44.1","@types/node":"^20.14.1","@types/react":"^18.0.28","@types/react-dom":"^18.0.11","@vitejs/plugin-react":"^4.0.0","autoprefixer":"^10.4.19","concurrently":"^8.2.2","eslint":"^8.43.0","eslint-config-airbnb":"^19.0.4","eslint-config-prettier":"^9.1.0","eslint-plugin-import":"^2.27.5","eslint-plugin-jsx-a11y":"^6.7.1","eslint-plugin-prettier":"^5.1.3","eslint-plugin-react":"^7.32.2","eslint-plugin-react-hooks":"^4.6.0","husky":"^8.0.0","knip":"^4.6.0","postcss":"^8.4.38","prettier":"^3.3.2","tailwindcss":"^3.4.3","typescript":"^5.4.5","vite":"^5.0.0","vitest":"^1.6.0","@emailjs/browser":"^3.11.0","@headlessui/react":"^2.1.2","@hookstate/core":"^4.0.1","@tanstack/react-query":"^5.22.2","@tanstack/react-query-devtools":"^5.24.0","@tanstack/react-table":"^8.17.3","axios":"^1.6.1","class-variance-authority":"^0.7.0","clsx":"^2.1.1","date-fns":"^2.30.0","html-react-parser":"^5.0.6","lucide-react":"^0.395.0","million":"^3.0.2","prop-types":"^15.8.1","react":"^18.2.0","react-dom":"^18.2.0","react-fast-marquee":"^1.6.2","react-helmet-async":"^2.0.5","react-hook-form":"^7.48.2","react-hot-toast":"^2.4.1","react-icons":"^5.2.1","react-lazy-load-image-component":"^1.6.0","react-photo-album":"^2.3.0","react-router-dom":"^6.11.2","react-share":"^5.1.0","react-simple-wysiwyg":"^2.2.5","recharts":"^2.12.7","tailwind-merge":"^2.3.0","tailwind-scrollbar-hide":"^1.1.7","tailwindcss-animate":"^1.0.7","yet-another-react-lightbox":"^3.15.6"})
> [15:56:09.343] Error: Command "pnpm install" exited with 1
> [15:56:09.568]
> ```

I also had an issue in deployment preview I used this logs to fix them turns out the issue is because there are discrepancies between the `pnpm-lock.yaml` file and the `package.json`. To fix it make sure the  `package.json` and `pnpm-lock.yaml` are both synchronized by running `pnpm install`.

**Review by JimmyTron — APPROVED** [review]

**Pull request merged**
